// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20230305071323_seedUser")]
    partial class seedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("WebApplication2.Models.Client", b =>
                {
                    b.Property<int?>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Client_Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Client_Id = 1,
                            Address = "7 Carnarvon Crescent",
                            City = "Stanhope Garden",
                            Country = "Australia",
                            Email = "Ashley.Martinez@financeteam.net",
                            FirstName = "Ashley ",
                            LastName = "Martinez",
                            Phone = "0412 345 678",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 2,
                            Address = "24 Teakwood Drive",
                            City = "Narre Warren South",
                            Country = "Australia",
                            Email = "John.Williams@moneyplus.com",
                            FirstName = "John",
                            LastName = "Williams",
                            Phone = "0432 123 456",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 3,
                            Address = "29 Rofe Street",
                            City = "Leichhardt",
                            Country = "Australia",
                            Email = "Jessica.Smith@finance.com",
                            FirstName = "Jessica",
                            LastName = "Smith",
                            Phone = "0421 987 654",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 4,
                            Address = "14 Elsom Street",
                            City = "South Windsor",
                            Country = "Australia",
                            Email = "Tyler.Johnson@investoradvisor.net",
                            FirstName = "Tyler",
                            LastName = "Davis",
                            Phone = "0456 789 012",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 5,
                            Address = "5 View Road",
                            City = "Springwood",
                            Country = "Australia",
                            Email = "Samantha.Davis@finance.com",
                            FirstName = "Samantha",
                            LastName = "Brown",
                            Phone = "0401 234 567",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 6,
                            Address = "5 Norman Street",
                            City = " Doncaster",
                            Country = "Australia",
                            Email = "David.Brown@moneywise.com.au",
                            FirstName = "David",
                            LastName = "Rodriguez",
                            Phone = "0437 456 789",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 7,
                            Address = "16 Rydges Street",
                            City = "South Wentworthville",
                            Country = "Australia",
                            Email = "Maria.Rodriguez@finance.com",
                            FirstName = "Maria",
                            LastName = "Anderson",
                            Phone = "0423 210 987",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 8,
                            Address = "4 Bluebell Circuit",
                            City = "Coffs Harbour",
                            Country = "Australia",
                            Email = "Kevin.Anderson@finance.com",
                            FirstName = "Kevin",
                            LastName = "Wilson",
                            Phone = "0445 678 901",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 9,
                            Address = "21 Willow Crescent",
                            City = " Footscray",
                            Country = "Australia",
                            Email = "Olivia.Wilson@finance.com",
                            FirstName = "Olivia",
                            LastName = "Miller",
                            Phone = "0409 876 543",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 10,
                            Address = "25 Tiernan Street",
                            City = "Mount Druitt",
                            Country = "Australia",
                            Email = "Michael.Miller@@financialadvice.net",
                            FirstName = "Michael",
                            LastName = "Taylor",
                            Phone = "0434 321 098",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 11,
                            Address = "2/49 Acacia Street",
                            City = "Mandurah",
                            Country = "Australia",
                            Email = "Sarah.Taylor@finance.com",
                            FirstName = "Sarah",
                            LastName = "Thompson",
                            Phone = "0415 678 901",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 12,
                            Address = "1/23 Hollis Street",
                            City = " Bonbeach",
                            Country = "Australia",
                            Email = "Christopher.Thompson@finance.com",
                            FirstName = "Christopher",
                            LastName = "Jackson",
                            Phone = "0426 543 210",
                            State = "WA"
                        },
                        new
                        {
                            Client_Id = 13,
                            Address = "15 Giselle Avenue",
                            City = "Mosman",
                            Country = "Australia",
                            Email = "Emily.Jackson@moneycoach.com",
                            FirstName = "Joshua",
                            LastName = "Lewis",
                            Phone = "0450 987 654",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 14,
                            Address = "2/6 Belmont Road",
                            City = "Buddina",
                            Country = "Australia",
                            Email = "Joshua.Lewis@finance.com",
                            FirstName = "Elizabeth",
                            LastName = "Clark",
                            Phone = "0407 321 098",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 15,
                            Address = "34 Orana Parade",
                            City = "Penrith",
                            Country = "Australia",
                            Email = "Elizabeth.Clark@finance.com",
                            FirstName = "Daniel",
                            LastName = "Lee",
                            Phone = "0439 876 543",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 16,
                            Address = "9 Carey Street",
                            City = " Bossley Park",
                            Country = "Australia",
                            Email = "Daniel.Lee@@financetoday.net",
                            FirstName = "Taylor",
                            LastName = "Hall",
                            Phone = "0418 765 432",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 17,
                            Address = "42 Mimosa Road",
                            City = "Smithfield",
                            Country = "Australia",
                            Email = "Taylor.Hall@finance.com",
                            FirstName = "Matthew",
                            LastName = "Wright",
                            Phone = "0429 012 345",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 18,
                            Address = "27 Pirrama Road",
                            City = "Ocean Grove",
                            Country = "Australia",
                            Email = "Matthew.Wright@finance.com",
                            FirstName = "Madison",
                            LastName = "Scott",
                            Phone = "0441 234 567",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 19,
                            Address = "14 Long Street",
                            City = "Pakenham",
                            Country = "Australia",
                            Email = "Madison.Scott@finance.com",
                            FirstName = "Andrew",
                            LastName = "Perez",
                            Phone = "0405 876 543",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 20,
                            Address = "3/25 Lake Avenue",
                            City = "Laverton",
                            Country = "Australia",
                            Email = "Andrew.Perez@yourfinancials.com",
                            FirstName = "Alyssa",
                            LastName = "Cooper",
                            Phone = "0430 210 987",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 21,
                            Address = "1/12 Station Street",
                            City = "Rothwell",
                            Country = "Australia",
                            Email = "Alyssa.Cooper@finance.com",
                            FirstName = "Robert",
                            LastName = "Baker",
                            Phone = "0413 456 789",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 22,
                            Address = "13 Neville Avenue",
                            City = "Carlton",
                            Country = "Australia",
                            Email = "Robert.Baker@moneymentor.net",
                            FirstName = "Lauren",
                            LastName = "Turner",
                            Phone = "0424 321 098",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 23,
                            Address = "16 Vaucluse Place",
                            City = "Coorparoo",
                            Country = "Australia",
                            Email = "Lauren.Turner@finance.com",
                            FirstName = "William",
                            LastName = "Gonzalez",
                            Phone = "0453 654 321",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 24,
                            Address = "4/1 Hampton Court Road",
                            City = "Thornleigh",
                            Country = "Australia",
                            Email = "William.Gonzalez@financialadvice.net",
                            FirstName = "Rachel",
                            LastName = "Adams",
                            Phone = "0408 765 432",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 25,
                            Address = "1/2 Marday Street",
                            City = "Padbury",
                            Country = "Australia",
                            Email = "Rachel.Adams@finance.com",
                            FirstName = "James ",
                            LastName = "Wright",
                            Phone = "0436 012 345",
                            State = "NSW"
                        },
                        new
                        {
                            Client_Id = 26,
                            Address = "46 Holt Parade",
                            City = "Geelong West",
                            Country = "Australia",
                            Email = "James.Wright@wealthbuilder.net",
                            FirstName = "Victoria",
                            LastName = "Nelson",
                            Phone = "0417 654 321",
                            State = "WA"
                        },
                        new
                        {
                            Client_Id = 27,
                            Address = "23 Howard Road",
                            City = "Burleigh Waters",
                            Country = "Australia",
                            Email = "Victoria.Nelson@yourwealth.com",
                            FirstName = "Benjamin",
                            LastName = "Johnson",
                            Phone = "0428 901 234",
                            State = "VIC"
                        },
                        new
                        {
                            Client_Id = 28,
                            Address = "9 Panorama Avenue",
                            City = "Anytown",
                            Country = "Australia",
                            Email = "Benjamin.Flores@moneyplan.net",
                            FirstName = "Grace",
                            LastName = "Flores",
                            Phone = "0440 543 210",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 29,
                            Address = "10 Dolly Avenue",
                            City = "Clontarf",
                            Country = "Australia",
                            Email = "Grace.Mitchell@finance.com",
                            FirstName = "Jane",
                            LastName = "Mitchell",
                            Phone = "0406 789 012",
                            State = "QLD"
                        },
                        new
                        {
                            Client_Id = 30,
                            Address = "8 O'Grady Street",
                            City = "Coorparoo",
                            Country = "Australia",
                            Email = "Nicholas.Collins@finance.com",
                            FirstName = "Nicholas",
                            LastName = "Collins",
                            Phone = "0431 234 567",
                            State = "QLD"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Notification", b =>
                {
                    b.Property<int?>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Task_Id")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Notification_Id");

                    b.HasIndex("Task_Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebApplication2.Models.Project", b =>
                {
                    b.Property<int?>("Project_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Client_Id")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Project_Id");

                    b.HasIndex("Client_Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Project_Id = 50,
                            Client_Id = 1,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial Analysis Report",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 51,
                            Client_Id = 2,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = " Business Plan Development",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 52,
                            Client_Id = 4,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = " Tax Compliance Audit",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 53,
                            Client_Id = 4,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Risk Assessment Strategy",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 54,
                            Client_Id = 5,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Planning and Analysis",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 55,
                            Client_Id = 6,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Market Research and Analysis",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 56,
                            Client_Id = 7,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Investment Portfolio Management",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 57,
                            Client_Id = 8,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accounting System Implementation",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 58,
                            Client_Id = 8,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cost Optimization Initiative",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 59,
                            Client_Id = 10,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corporate Social Responsibility ",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 60,
                            Client_Id = 10,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial Analysis Report",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 61,
                            Client_Id = 12,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Market Research and Analysis",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 62,
                            Client_Id = 15,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = " Accounting System Implementation",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 63,
                            Client_Id = 14,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Business Plan Development",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 64,
                            Client_Id = 15,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corporate Social Responsibility Program",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 65,
                            Client_Id = 16,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cost Optimization Initiative",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 66,
                            Client_Id = 17,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tax Compliance Audit",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 67,
                            Client_Id = 18,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Risk Assessment Strategy",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 68,
                            Client_Id = 19,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Market Research and Analysis",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 69,
                            Client_Id = 20,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Investment Portfolio Management",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 70,
                            Client_Id = 20,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial Analysis Report",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 71,
                            Client_Id = 20,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = " Corporate Social Responsibility Program",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 72,
                            Client_Id = 23,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accounting System Implementation",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 73,
                            Client_Id = 24,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Business Plan Development",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 74,
                            Client_Id = 25,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Risk Assessment Strategy",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 75,
                            Client_Id = 26,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Market Research and Analysis",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 76,
                            Client_Id = 22,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cost Optimization Initiative",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 77,
                            Client_Id = 28,
                            DueDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial Analysis Report",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 78,
                            Client_Id = 29,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = " Corporate Social Responsibility Program",
                            Status = "On going"
                        },
                        new
                        {
                            Project_Id = 79,
                            Client_Id = 28,
                            DueDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Risk Assessment Strategy",
                            Status = "On going"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Task1", b =>
                {
                    b.Property<int?>("Task_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Project_Id")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TimeEstimate")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<int?>("User_Id")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.HasKey("Task_Id");

                    b.HasIndex("Project_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WebApplication2.Models.User", b =>
                {
                    b.Property<int?>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job_Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OnLeave")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Registration_date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("User_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 100,
                            Email = "johndoe@admin.com",
                            FirstName = "John",
                            Job_Title = "Resource Manager ",
                            LastName = "Doe",
                            OnLeave = false,
                            Password = "Password123",
                            Phone = "0422 123 456",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7265),
                            Role = "Admin"
                        },
                        new
                        {
                            User_Id = 101,
                            Email = "alicesmith@financeteam.com",
                            FirstName = "Alice",
                            Job_Title = "Financial Analyst ",
                            LastName = "Smith",
                            OnLeave = false,
                            Password = "Summer2023",
                            Phone = "0413 456 789",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7285),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 102,
                            Email = "danieljohnson@financeteam.com",
                            FirstName = "Daniel ",
                            Job_Title = "Investment Banker ",
                            LastName = "Johnson",
                            OnLeave = false,
                            Password = "Pineapple21",
                            Phone = "0438 987 654",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7287),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 103,
                            Email = "evaortiz@financeteam.com",
                            FirstName = "Eva",
                            Job_Title = "Risk Manager ",
                            LastName = "Ortiz",
                            OnLeave = true,
                            Password = "BlueBird20",
                            Phone = "0488 765 432",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7289),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 104,
                            Email = "mikewang@financeteam.com",
                            FirstName = "Mike",
                            Job_Title = "Accountant ",
                            LastName = "Wang",
                            OnLeave = false,
                            Password = "LovelyDay22",
                            Phone = "0400 555 666",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7291),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 105,
                            Email = "chrisbrown@financeteam.com",
                            FirstName = "Chris",
                            Job_Title = "Financial Planner ",
                            LastName = "Brown",
                            OnLeave = false,
                            Password = "Happy2023!",
                            Phone = "0456 888 777",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7293),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 106,
                            Email = "sarafoster@financeteam.com",
                            FirstName = "Sara",
                            Job_Title = "Credit Analyst ",
                            LastName = "Foster",
                            OnLeave = false,
                            Password = "Secret123",
                            Phone = "0499 222 111",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7295),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 107,
                            Email = "mattdavis@financeteam.com",
                            FirstName = "Matt",
                            Job_Title = "Treasury Analyst ",
                            LastName = "Davis",
                            OnLeave = true,
                            Password = "CoolCat21",
                            Phone = "0424 333 222",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7297),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 108,
                            Email = "lucychen@financeteam.com",
                            FirstName = "Lucy",
                            Job_Title = "Asset Manager ",
                            LastName = "Chen",
                            OnLeave = false,
                            Password = "GoldenSun22",
                            Phone = "0432 111 333",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7299),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 109,
                            Email = "tomcoleman@financeteam.com",
                            FirstName = "Tom",
                            Job_Title = "Compliance Officer ",
                            LastName = "Coleman",
                            OnLeave = false,
                            Password = "StarrySky20",
                            Phone = "0444 888 222",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7300),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 110,
                            Email = "amykim@financeteam.com",
                            FirstName = "Amy",
                            Job_Title = "Actuary ",
                            LastName = "Kim",
                            OnLeave = false,
                            Password = "RedRose2023",
                            Phone = "0465 222 333",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7302),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 111,
                            Email = "johnpowell@financeteam.com",
                            FirstName = "John",
                            Job_Title = "Tax Advisor ",
                            LastName = "Powell",
                            OnLeave = true,
                            Password = "Mountain21",
                            Phone = "0477 333 111",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7304),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 112,
                            Email = "jessicahoward@financeteam.com",
                            FirstName = "Jessica",
                            Job_Title = "Auditor  ",
                            LastName = "Howard",
                            OnLeave = false,
                            Password = "CrazyBird22",
                            Phone = "0405 444 555",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7305),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 113,
                            Email = "gabrielholland@financeteam.com",
                            FirstName = "Gabriel",
                            Job_Title = "Controller ",
                            LastName = "Holland",
                            OnLeave = false,
                            Password = "OceanView23",
                            Phone = "0411 666 555",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7307),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 114,
                            Email = "daviscox@financeteam.com",
                            FirstName = "Davis",
                            Job_Title = "Portfolio Manager ",
                            LastName = "Cox",
                            OnLeave = true,
                            Password = "BrightSun20",
                            Phone = "0455 777 444",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7309),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 115,
                            Email = "ashleysimpson@financeteam.com",
                            FirstName = "Ashley",
                            Job_Title = "Wealth Manager  ",
                            LastName = "Simpson",
                            OnLeave = false,
                            Password = "Dancing21!",
                            Phone = "0423 888 333",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7311),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 116,
                            Email = "chris.brown@financeteam.com",
                            FirstName = "Christophe",
                            Job_Title = "Insurance Underwriter",
                            LastName = "Brown",
                            OnLeave = false,
                            Password = "Peaceful22",
                            Phone = "0409 555 777",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7313),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 117,
                            Email = "sara.lee@financeteam.com",
                            FirstName = "Sara",
                            Job_Title = "Budget Analyst  ",
                            LastName = "Lee",
                            OnLeave = false,
                            Password = "SunnyDay23",
                            Phone = "0467 777 444",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7315),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 118,
                            Email = "lily.larson@financeteam.com",
                            FirstName = "Lily",
                            Job_Title = "Corporate Finance Manager",
                            LastName = "Larson",
                            OnLeave = true,
                            Password = "Joyful21",
                            Phone = "0498 444 888",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7316),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 119,
                            Email = "isaac.chen@financeteam.com",
                            FirstName = "Isaac ",
                            Job_Title = "Financial Consultant ",
                            LastName = "Chen",
                            OnLeave = false,
                            Password = "SilverMoon20",
                            Phone = "0426 555 666",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7318),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 120,
                            Email = "elijah.rivera@financeteam.com",
                            FirstName = "Elijah",
                            Job_Title = "Loan Officer ",
                            LastName = "Rivera",
                            OnLeave = false,
                            Password = "LuckyDay22",
                            Phone = "0435 666 888",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7320),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 121,
                            Email = "julian.kim@financeteam.com",
                            FirstName = "Julian",
                            Job_Title = "Financial Advisor ",
                            LastName = "Kim",
                            OnLeave = true,
                            Password = "PurpleRain23",
                            Phone = "0472 333 555",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7321),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 122,
                            Email = "john.murphy@financeteam.com",
                            FirstName = "John",
                            Job_Title = "Data Analyst ",
                            LastName = "Murphy",
                            OnLeave = false,
                            Password = "WildFlower21",
                            Phone = "0431 777 666",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7323),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 123,
                            Email = "adrian.webb@financeteam.com",
                            FirstName = "Adrian ",
                            Job_Title = "Procurement Specialist ",
                            LastName = "Webb",
                            OnLeave = false,
                            Password = "HappyHour20!",
                            Phone = "0480 888 777",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7324),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 124,
                            Email = "bob.sanders@financeteam.com",
                            FirstName = "Bob",
                            Job_Title = " Financial Advisor",
                            LastName = "Sanders",
                            OnLeave = false,
                            Password = "Morning22",
                            Phone = "0407 555 222",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7326),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 125,
                            Email = "eva.ross@financeteam.com",
                            FirstName = "Eva",
                            Job_Title = " Supply Chain Manager",
                            LastName = "Ross",
                            OnLeave = true,
                            Password = "OceanBreeze23",
                            Phone = "0461 777 888",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7328),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 126,
                            Email = "mike.wang@financeteam.comm",
                            FirstName = "Mike",
                            Job_Title = " Investment Banker",
                            LastName = "Wang",
                            OnLeave = false,
                            Password = "Chocolate21",
                            Phone = "0434 555 777",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7330),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 127,
                            Email = "chris.brown@financeteam.com",
                            FirstName = "Chris",
                            Job_Title = "Management Consultant ",
                            LastName = "Brown",
                            OnLeave = false,
                            Password = "GreenTree22",
                            Phone = "0429 666 111",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7331),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 128,
                            Email = "sara.sanchez@financeteam.com",
                            FirstName = "Sara",
                            Job_Title = " Sales Manager",
                            LastName = "Sanchez",
                            OnLeave = false,
                            Password = "SnowyDay20",
                            Phone = "0452 888 666",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7333),
                            Role = "User"
                        },
                        new
                        {
                            User_Id = 129,
                            Email = "mia.bryant@financeteam.com",
                            FirstName = "Mia ",
                            Job_Title = "Business Developer",
                            LastName = "Bryant",
                            OnLeave = true,
                            Password = "Diamond2023",
                            Phone = "0479 555 444",
                            Registration_date = new DateTime(2023, 3, 5, 18, 13, 23, 213, DateTimeKind.Local).AddTicks(7335),
                            Role = "User"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.UserRecord", b =>
                {
                    b.Property<int?>("UserRecord_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Task_Id")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserRecord_Id");

                    b.HasIndex("Task_Id");

                    b.ToTable("UserRecords");
                });

            modelBuilder.Entity("WebApplication2.Models.Notification", b =>
                {
                    b.HasOne("WebApplication2.Models.Task1", "Task")
                        .WithMany("Notification")
                        .HasForeignKey("Task_Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WebApplication2.Models.Project", b =>
                {
                    b.HasOne("WebApplication2.Models.Client", "Client")
                        .WithMany("Project")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApplication2.Models.Task1", b =>
                {
                    b.HasOne("WebApplication2.Models.Project", "Project")
                        .WithMany("Task")
                        .HasForeignKey("Project_Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("WebApplication2.Models.User", "User")
                        .WithMany("Task")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication2.Models.UserRecord", b =>
                {
                    b.HasOne("WebApplication2.Models.Task1", "Task")
                        .WithMany("UserRecords")
                        .HasForeignKey("Task_Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WebApplication2.Models.Client", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("WebApplication2.Models.Project", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("WebApplication2.Models.Task1", b =>
                {
                    b.Navigation("Notification");

                    b.Navigation("UserRecords");
                });

            modelBuilder.Entity("WebApplication2.Models.User", b =>
                {
                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
